topology:
  host_interfaces:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
  VMs:
    Port01T1:
      vlans:
        - 30
      vm_offset: 0
    Port02T1:
      vlans:
        - 31
      vm_offset: 1
  DUT:
    vlan_configs:
      default_vlan_config: one_vlan_a
      one_vlan_a:
        Vlan1000:
          id: 1000
          intfs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
          prefix: 192.168.0.1/21
          tag: 1000

configuration_properties:
  common:
    dut_asn: 65100
    dut_type: ToRRouter
    swrole: leaf
    nhipv4: 10.10.246.254
    nhipv6: FC0A::FF
    
    traffic_common:
    linerate: 100
    framesize: 64

configuration:
  Port01T1:
    properties:
    - common
    bgp:
      asn: 64600
      peers:
        65100:
        - 10.10.10.1
        - FC00::71
    interfaces:
      Ethernet116:
        ipv4: 10.10.10.2/24
        ipv6: fc00::72/126

  Port02T1:
    properties:
    - common
    bgp:
      asn: 64600
      peers:
        65100:
        - 10.20.10.1
        - FC00::75
    interfaces:
      Ethernet120:
        ipv4: 10.20.10.2/24
        ipv6: fc00::76/126
    
  TrafficItem1:
    properties:
    - traffic_common
    endpoints:
      src: Port1T1
      dst: Port2T1

  TrafficItem2:
    properties:
    - traffic_common
    endpoints:
      src: Port3T1
      dst: Port4T1
